version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis
    # Using nodemon for hot reload in dev inside docker
    command: npm run dev

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    
    depends_on:
      - redis
      - server
    

volumes:
  redis_data:
